# cargo-deny configuration.
# License gate enforces our rule: permissive deps only — NO GPL code may be linked.
# (Techniques from GPL tools like abraunegg/onedrive are re-implemented, never copied.)

[advisories]
version = 2
yanked = "deny"

[licenses]
version = 2
allow = [
    "Apache-2.0",
    "MIT",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "0BSD",
    "ISC",
    "Zlib",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "MPL-2.0",
    "CC0-1.0",
]
confidence-threshold = 0.9

[bans]
multiple-versions = "warn"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
